# File .chipperci.yml, which goes in the root of your repository
version: 1

environment:
  php: 8.1    # 7.1, 7.2, 7.3, 7.4, 8.0, 8.1
  node: 16    # 6, 8, 10, 12, 14, 16

#services:
#  - mysql: 5.7

pipeline:
  - name: Setup
    cmd: |
      cp -v .env.example .env
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate

  - name: Compile Dev Assets
    cmd: |
      npm ci --no-audit
      npm run build # Vite
      # npm run dev # Mix
      
  - name: Prepare
    cmd: |
      sudo apt update 
      sudo apt install bc -y
      sudo apt-get --only-upgrade install google-chrome-stable
      npm install -g node-sass
      composer require --dev laravel/dusk
      php artisan dusk:install
      php artisan dusk:chrome-driver --detect
      sudo chmod -R 0755 vendor/laravel/dusk/bin/
      sudo chmod -R 0755 vendor/laravel/dusk/bin/. 

  - name: Install cypress
    cmd: | 
      sudo apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      npm install cypress --save-dev
      composer require laracasts/cypress --dev
      php artisan cypress:boilerplate
   
  - name: Run Tests
    cmd: |
      php artisan serve 2>/dev/null &

      if [[ $CI_COMMIT_MESSAGE == 'record' ]]; then
          npx cypress run --record --key b6c7add4-a312-469f-8dbc-93e3fc3e0871 --env CYPRESS_BASE_URL=http://l27.0.0.1:8000 --browser chrome # record testing on cypress cloud
      elif [[ $CI_COMMIT_MESSAGE == 'example' ]]; then
          npx cypress run --spec "tests/cypress/integration/example.cy.js" --env CYPRESS_BASE_URL=http://l27.0.0.1:8000 --browser chrome # record testing on cypress cloud
      else
          npm run cy:run  # run cypress tests
      fi